name: Wrapper Validation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  gradle-wrapper:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Validate Wrapper
        uses: gradle/wrapper-validation-action@v2
